# -*- coding: utf-8 -*-
"""app.ipy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14UsgJ5DnEtFJiQsn_hDApCU3EK9Z5euV
"""

pip install streamlit

pip install -U ultralytics

pip install feedparser

#%%writefile app.py

# Import the libraries
import streamlit as st
from ultralytics import YOLO
from PIL import Image
import cv2
import numpy as np
import feedparser
from datetime import datetime

# Configure page
st.set_page_config(page_title="WA Bushfire Detector", page_icon="🔥", layout="wide")
st.title("🔥 WA Bushfire Detector")
st.markdown("**AI-powered bushfire detection + official WA alerts** (built with ❤️ in Perth)")

# Cache/store the model and load
@st.cache_resource
def load_model():
  return YOLO("pyronear/yolov8s.pt") # Direct from Hugging Face

model = load_model()

# Tabs
tab1, tab2, tab3 = st.tabs(["🖼️ AI Detection", "🚨 Current WA Incidents", "🗺️ Bushfire Prone Areas"])

# Tab 1: AI DETECTION
with tab1:
  st.header("Upload an image to detect fire/smoke")
  st.write("Works great with drone, trail cam, or phone photos from WA bushland.")

  uploaded_file = st.file_uploader("Choose image....", type=["jpg", "jpeg", "png"])

  if uploaded_file is not None: # If the uploaded image is of type jpg, jpeg or png
    image = Image.open(uploaded_file)
    img_array = np.array(image)

    # Run detection
    results = model(img_array, conf=0.25, iou=0.45)

    # Draw boxes
    annotated = results[0].plot()

    col1, col2 = st.columns(2)
    with col1:
      st.image(image, caption="Original", use_column_width=True)
    with col2:
      st.image(annotated, caption="🔥 Detected fire/smoke areas", use_column_width=True)


    # Summary
    detections = results[0].boxes
    if len(detections) > 0: #ie if there are detections
      st.success(f"🚨 **ALERT**: {len(detections)} fire/smoke detection(s) found!")
      for box in detections:
        cls = int(box.cls[0])
        conf = float(box.conf[0])
        class_name = model.names[cls]
        st.write(f"• **{class_name}** detected with {conf:.1%} confidence")

      else:
        st.info("✅ No fire or smoke detected in this image.")

# Tab 2: Current WA Incidents

with tab2:
  st.header("Current Bushfire Incidents in WA")
  st.write("Live from official Emergency WA sources (updated every few minutes)")


  # RSS feeds (you can add more)
  feeds= {
      "DFES Warnings": "https://www.emergency.wa.gov.au/feeds/dfeswarnings.rss",
      "DFES Incidents": "https://www.emergency.wa.gov.au/feeds/incidents.rss"  # Check exact URL on emergency.wa.gov.au/about
}

for name, url in feeds.items():
  try: # try the below if name and urls are found in the feeds item
    feed = feedparser.parse(url)
    st.subheader(f"**{name}**")
    for entry in feed.entries[:5]: # Show the latest 5
      published = entry.get('published', 'No date')
      st.markdown(f"**{entry.title}**  \n{published}  \n[Read more]({entry.link})")
  except:# if not found
    st.warning(f"Could not load {name} feed. Visit [Emergency WA](https://www.emergency.wa.gov.au) directly.")

st.markdown("---")
st.markdown("[Open full interactive map →](https://www.emergency.wa.gov.au)")

# Tab 3: Bushfire prone areas
st.header("Bushfire Prone Areas in Western Australia")
st.image("https://www.dfes.wa.gov.au/hazard-information/bushfire/bushfire-prone-areas", caption="Official Map (click to enlarge)", use_column_width=True)
st.markdown("""
**Download the full dataset** (shapefile for GIS use):
→ [Bush Fire Prone Areas 2024 (data.wa.gov.au)](https://catalogue.data.wa.gov.au/dataset/bush-fire-prone-areas-2024-obrm-021)
""")

# Sidebar
with st.sidebar:
  st.header("About")
  st.write("This app uses a **Hugging Face** wildfire detection model trained on real bushfire imagery.")
  st.write("Perfect for landholders, fire brigades, or anyone in high-risk WA areas (Perth Hills, South West, Wheatbelt, etc.).")

  st.markdown("---")
  st.caption("Made for Western Australia 🇦🇺 | February 2026")

#!curl https://loca.lt/mytunnelpassword

#!streamlit run app.py &>/content/logs.txt &
#!npx localtunnel --port 8501